version: 2.1

jobs:
  build:
    docker:
      - image: emscripten/emsdk:3.1.21
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          keys:
            - opencv-cache-{{ arch }}-{{ .Branch }}-{{ checksum ".git/modules/opencv/HEAD" }}
      - run:
          name: Build with emscripten
          command: |
            emcmake cmake . -B build
            cmake --build build
      - save_cache:
          key: opencv-cache-{{ arch }}-{{ .Branch }}-{{ checksum ".git/modules/opencv/HEAD" }}
          paths:
            - build/opencv-build
            - build/opencv-install
            - build/opencv-prefix
      - store_artifacts:
          path: build/web

workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master
