version: 2.1

jobs:
  build:
    docker:
      - image: emscripten/emsdk:3.1.21
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Build with emscripten
          command: |
            emcmake cmake . -B build
            cmake --build build
      - store_artifacts:
          path: build/web

workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master
